services:
  db:
    restart: unless-stopped

  api:
    restart: unless-stopped
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 2
    volumes: []
    env_file:
      - .env.prod

  web:
    restart: unless-stopped
    env_file:
      - .env.prod
